from pathlib import Path
import csv
P=Path(__file__).parent
fields='candidate_id,me_id,category,manufacturer,model,qty,unit,currency,listed_price,tax_basis,tax_rate,net_unit_price,price_url,spec_url,length_mm,width_mm,height_mm,mass_kg,technical_status,scope_notes,availability,access_date'.split(',')
rows=[]
def add(id,me,cat,mfr,model,qty='',price='',tax='',rate='',net='',url='',spec='',dims=('', '', ''),mass='',status='TECH_OPEN',notes='',avail='NOT_CONFIRMED'):
 rows.append(dict(zip(fields,[id,me,cat,mfr,model,qty,'шт','EUR',price,tax,rate,net,url,spec,*dims,mass,status,notes,avail,'2026-09-11'])))
aqua='https://www.aquatec-watermaker.de/wassermacher-produkt-ac150-ac240.html'
schenk='https://schenkerwatermakers.com/wp-content/uploads/2025/03/ZEN150_datasheet_v4.pdf'
osmo='https://osmosea.it/en/new-12/'
add('WC-RO-01','ME-13','RO150','Aquatec','AC150 230V single phase',1,7539,'EXPLICIT_NET_AND_19_PERCENT_GROSS',19,6335.29,aqua,aqua,status='FUNCTION_PARITY_OPEN;220V_COMPATIBILITY_OPEN',notes='150 L/h nominal ±10% at25C/35000ppm; modular conventional HP pump; base price only: automatic flush/salinity/reject parity must be itemised; generator minimum4kW manufacturer target, not electrical demand or selection')
add('WC-RO-02','ME-13','RO150','Schenker','ZEN150 24V/230V Touch plus salinity/reject',1,12820.20,'FROM_GROSS_EXPLICIT_20_PERCENT',20,10683.50,'https://mar-nautic.com/schenker-watermaker-zen-150',schenk,status='FROM_PRICE_NOT_CONFIGURED;RFQ_REQUIRED',notes='Observed FROM base price; net is FROM benchmark only, NOT complete Touch/salinity/reject price. Nominal150L/h. Manufacturer230V±15% includes220V. Basic has no salinity; Touch optional; 24V variant permitted. Modular unit dimensions not total installed envelope.',avail='Out of stock; order lead time on request')
add('WC-RO-03','ME-13','RO150','Osmosea','NEW12 150C 24V',1,url='https://www.manelservice.com/en/marine-desalination-systems/17102-osmosea-new12-150c-nautical-watermaker-150-lth.html',spec=osmo,mass=63,status='RFQ_REQUIRED;COMPACT_CANDIDATE',notes='Official150L/h/600W; flush/salinometer/unsafe-water discard included. Official63kg conflicts dealer65kg; dimensions dealer796x317x408 not official therefore blank. Dealer install/service kits included vs manufacturer optional: reconcile')
gia='https://www.gianneschipumps.com/GIANNESCHI_Brochure-web.pdf'
cem='https://cempumps.com/wp-content/uploads/2024/10/Autoclavi_20L-20X.pdf'
enag='https://www.enag.fr/english/wp-content/uploads/sites/5/2022/11/FC-GH-EN-C.pdf'
add('WC-DC-01','ME-11','FRESHWATER_24V','CEM','OSC-16.062.24 / OEM identity reconcile',1,1229.90,'EXPLICIT_HT', '',1024.92,'https://www.comptoirnautique.com/groupe-d-eau-a-pressostat/53022-cem-elettromeccanica-autoclave-cem-vase-expansion-inox-20l-24v-50-l-min.html',cem,status='WORKING_POINT_AND_OEM_ID_OPEN',notes='24V20L accumulator; dealer50L/min max; source model mapping not proven. Common proposed test15L/min at2bar NOT verified. Do not add included tank again.',avail='Preorder; replenishment23/09/2026')
add('WC-DC-02','ME-11','FRESHWATER_24V','Gianneschi','EcoInox1 GE011 24V20L',1,1311.90,'EXPLICIT_HT','',1093.25,'https://www.comptoirnautique.com/groupe-d-eau-hydrophore/22947-gianneschi-groupe-d-eau-ecoinox-1-avec-reservoir-20l-24v-45lmin-7024.html',gia,status='WORKING_POINT_OPEN',notes='45L/min max; common proposed15L/min at2bar needs curve. Includes20L tank/gauge/pressure switch; current OEM revision confirmation.',avail='In stock48/72h')
add('WC-DC-03','ME-11','FRESHWATER_24V','ENAG','GH24-0.37-24L-OT RB18-ED',1,url='https://www.enag.fr/english/wp-content/uploads/sites/5/2022/11/FC-GH-EN-C.pdf',spec=enag,mass=29,status='RFQ_REQUIRED;WORKING_POINT_OPEN',notes='Official24V/0.37kW; 1m3/h at30m published point; pressure switch1.5/2.5bar.24L tank differs20L competitors: standardise accumulator scope before comparison. Dimensions drawing orientation not mapped into LWH.')
add('WC-AC-01','ME-12','FRESHWATER_AC','CEM','J-INOX/20X 230M',1,url=cem,spec=cem,status='RFQ_REQUIRED;220V_COMPATIBILITY_OPEN;WORKING_POINT_OPEN',notes='Official230V singlephase variant exists. Proposedcommon15L/min at2bar not accepted from maxflow.20L stainless tank included. No price borrowed from24V sibling.')
add('WC-AC-02','ME-12','FRESHWATER_AC','Gianneschi','EcoInox2 GE017 230V20L',1,1263,'EXPLICIT_HT','',1052.50,'https://www.tyboat.com/achat/P-57388-gianneschi-groupe-d-eau-ecoinox2-3-5-bars-0-45-kw-55-litres-minute-reservoir-20-litres-230-volts.html',gia,status='220V_COMPATIBILITY_OPEN;WORKING_POINT_OPEN',notes='Open page1052.50HT supersedes search992.50. Dealer max55L/min conflicts Kent45: curves required.0.45kW/20L; common15L/min at2bar not verified.',avail='Stock1–6businessdays')
add('WC-AC-03','ME-12','FRESHWATER_AC','ENAG','GH230mono-0.37-24L-JET M-ED',1,url=enag,spec=enag,mass=18,status='RFQ_REQUIRED;220V_COMPATIBILITY_OPEN;WORKING_POINT_OPEN',notes='Explicit230V singlephase; official1m3/h at40m, pressure switch1.5/2.5bar.24L accumulator vs20L needs standardisation; no equivalence claim.')
webasto='https://www.webasto.com/en-us/cooling/marine-chiller-air-conditioning-units/bluecool-c-series.html'
thermo='https://www.thermowellmarine.com/wp-content/uploads/2023/04/THERMOWELL-2023_rev1_apr_web.pdf'
climma='https://www.veco.net/en/prodotti/climma-cws-aquacontrol-chillers/'
add('WC-CH-01','ME-15','CHILLER_REFERENCE_16000BTUH','Thermowell','UC16H',2,4544.35,'GROSS_EXPLICIT_ALV25.5',25.5,round(4544.35/1.255,2),'https://www.esconet.fi/shop/uc16h-thermowell-uc16h-ilmastointilaite-chiller-230v-16000btu-27518',thermo,(350,340,380),38,status='REFERENCE_SIZE_ONLY;VOLTAGE_REVISION_CHECK;SUPPLY_SCOPE_CONFLICT_RFQ',notes='16000BTU/h each; illustrative class NOT yacht heatload. Officialcatalog220/1/50; dealer230V. Dimensions exclude controlbox. OEM catalogue says box/display included BUT priced Esco SKU requires airhandler/controlpanel separately: inclusion CONFLICT, RFQ required; do not assume included display.1.5kWnominput at catalogue conditions; independent2module integration open.',avail='Esco stock0; supplier availability unknown')
add('WC-CH-02','ME-15','CHILLER_REFERENCE_16000BTUH','Climma','CWS Aquacontrol161RC 230/1/50',2,4155.30,'EXPLICIT_TAX_EXCLUDED','',4155.30,'https://mdislandsupply.com/en/climma/879-cws-aquacontrol-161-rc-230150-climma.html',climma,status='REFERENCE_SIZE_ONLY;220V_COMPATIBILITY_OPEN',notes='16000BTU/h each; reversecycle. Price recovered live requests HTTP200 after web429; local source text retained. OEM dimensions require authenticated download; old dealerPDF not promoted.',avail='Last items;1–2businessdays claim')
add('WC-CH-03','ME-15','CHILLER_REFERENCE_16000BTUH','Webasto','BlueCool C16M',2,url='https://www.nauticsale.com/en/airconditioning/bluecool-chiller-systems/bluecool-c-series-chillers/',spec=webasto,dims=(385,290,350),mass=30,status='RFQ_REQUIRED;REFERENCE_SIZE_ONLY;220V_COMPATIBILITY_OPEN',notes='16000BTU/h each; officialcurrentdimensions. Older F-suffix dealerweight differs: revision match required.3pricepaths found no verified EU net exactSKU; no US price conversion.')
for id,model,price,net,urlslug,name in [
('01','B3 40L1200W FLB34012S000A00',737,614.17,'P-8889-quick-chauffe-eau-cylindrique-b3-40-litres-220-volts-1200-watts','b3'),
('02','BX 40L1200W FLBX4012S000A00',829,690.83,'P-8880-quick-chauffe-eau-cylindrique-bx-40-litres-220-volts-1200-watts','bx'),
('03','BXS 40L1200W FLBXS4012S00A00',909,757.50,'P-18237-quick-chauffe-eau-cube-inox-bxs-40-litres-220-volts-1200-watts','bxs')]:
 add('WC-HW-'+id,'ME-14','BOILER_REFERENCE_40L','Quick',model,price=price,tax='EXPLICIT_HT',net=net,url='https://www.tyboat.com/achat/'+urlslug+'.html',spec='https://www.quickitaly.com/it/prodotti/scalda-acqua/scalda-acqua/nautic-boiler-'+name+'/',status='UNIT_BENCHMARK_ONLY;QTY_OPEN',notes='40L1200W220V plus engine heat exchanger common illustrative class; not owner size. Supplier dimensions/mass in research only pending official drawing. Thermostatic mixing equalise separately.',avail='Stock1–6businessdays')
add('WC-AUX-01','ME-16','HVAC_PUMP','Frigomar','NH150PS SWM0150230',price=795.90,tax='EXPLICIT_HT',net=663.25,url='https://www.comptoirnautique.com/climatisation-bateau/91819-frigomar-pompes-a-entrainement-magnetique.html',spec='https://www.frigomar.com/en/product-line/',status='UNIT_BENCHMARK_ONLY;CURVE_AND_220V_OPEN',notes='230V50/60Hz magneticdrive; count and pump duty notfixed. No proof this model meets both seawater and chilledwater circuits; official detailed curve required.',avail='Preorder; replenishment19/09/2026')
add('WC-AUX-02','ME-17','THERMOSTATIC_MIXING','Quick','QB002 mixing kit',price=140.40,tax='EXPLICIT_HT',net=117,url='https://www.kent-marine.com/fr/produit/35262/chauffe-eau-cylindrique-40l-220v-1200w.html',spec='https://www.quickitaly.com/it/prodotti/scalda-acqua/',status='PUBLIC_LIST_UNIT_BENCHMARK',notes='Observed linked accessory publicHT price; count unknown; confirm inclusion in selected calorifier supply.',avail='Not confirmed')
add('WC-AUX-03','ME-17','FRESHWATER_FILTER','Jabsco','Pumpgard36400-0002 / substitution46400-0000',price=33.50,tax='TAX_NOT_PROVEN',url='https://www.marine-impact.com/groupe-d-eau/313-filtre-en-ligne-pumpgard-o13-mm-jabsco.html',spec='https://www.xylem.com/siteassets/brand/jabsco/resources/manual/36800-technical-data-sheet.pdf',status='UNIT_BENCHMARK_GROSS_UNKNOWN;NET_WITHHELD',notes='Observedprice; no explicit taxbasis verified so net blank.13mm40mesh strainer not sanitary treatment and not dimensioned for proposedpressurestation.',avail='Web listing')
with (P/'candidates.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=fields,delimiter=';');w.writeheader();w.writerows(rows)
print('rows',len(rows),'net',sum(bool(r['net_unit_price']) for r in rows))
